# Generated by Django 4.2 on 2023-06-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='movies', upload_to='movies'),
            preserve_default=False,
        ),
    ]
